/// Typy oznaczające treść, której nie wolno zapisywać w historii (konwencja nspasteboard.org).
/// W WyspaCore, bo używają ich i historia schowka (pomija), i Szybkie akcje (oznaczają hasło).
public enum PasteboardPrivacy {
    public static let concealed = "org.nspasteboard.ConcealedType"
    public static let transient = "org.nspasteboard.TransientType"
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"

    /// Hasła z menedżerów haseł, treści tymczasowe i generowane automatycznie są pomijane.
    public static func shouldIgnore(types: [String]) -> Bool {
        types.contains(concealed) || types.contains(transient) || types.contains(autoGenerated)
    }
}
